sudo: required
services:
  - docker

before_install:
  - docker build -t amerej/devops-test-test -f ./client/Dockerfile.dev ./client

script:
  - docker run amerej/devops-test-test yarn test:unit -- --coverage

after_success:
  - docker build -t amerej/devops-test-client ./client
  - docker build -t amerej/devops-test-nginx ./nginx
  - docker build -t amerej/devops-test-server ./server
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker
  - docker push amerej/devops-test-client
  - docker push amerej/devops-test-nginx
  - docker push amerej/devops-test-server
